# Generated by Django 5.0.1 on 2024-03-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='category',
            field=models.CharField(choices=[('TITAN', 'Titan'), ('NOISE', 'Noise'), ('TIMEX', 'Timex'), ('NAVYFORCE', 'Navyforce')], max_length=20),
        ),
    ]
