# Generated by Django 5.0.1 on 2024-03-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_watch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='watch',
            name='price_and_quantity_total',
            field=models.IntegerField(default=0),
        ),
    ]
