# Generated by Django 5.0.1 on 2024-03-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='price_and_quantity_total',
        ),
    ]
